routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
 *
 *  Admin Routes
 *
 *
 *  */
 
 Route::get('/clear-cache', function() {
  $exitCode = Artisan::call('config:cache');
  return "Cache is cleared";
});
 Route::get('/jwt-secret', function() {
  $exitCode = Artisan::call('jwt:secret');
  return "Secret Key Generated";
});

Auth::routes(['verify'=>true]);
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/hotel-sale-report','HotelSaleReportController@index');
    Route::get('/hotel-sale-report/edit/{order}','HotelSaleReportController@editSale');
    Route::get('/AddhotelBuying','HotelReport@buyingadd')->name('addbuying');
    
    Route::get('/buyingItem','HotelBuyingItemController@index')->name('buyingItem');
    Route::post('/buy-report/print','HotelBuyingItemController@print');
    Route::post('/buy-report/data','HotelBuyingItemController@data');


    Route::get('/create-buying-item','HotelBuyingItemController@create')->name('createBuyingItem');
    Route::post('/store-buying-item','HotelBuyingItemController@store')->name('storeBuyingItem');
    Route::post('/savehotelBuying','HotelBuyingController@buyingsave')->name('savehotelbuying');
    Route::post('/updateKitchItem','HotelBuyingController@updateKitchItem')->name('updateKitchItem');
    Route::resource('/products','ProductsController');
    Route::resource('/categories', 'CategoriesController');
    Route::get('/search-data-hotel','HotelBuyingController@search')->name('searchhotelbuyingreport');
    Route::get('/search-inventory-hotel','HotelBuyingController@inventoryReport')->name('inventoryReport');
    Route::get('/totalBuying','HotelReport@buying')->name('buying');
    Route::get('/totalBuying/edit/{hotel}','HotelReport@buyingEdit')->name('edit.buying');
    Route::post('/totalBuying/edit/{hotel}','HotelReport@buyingUpdate')->name('update.buying');
    Route::post('/totalBuying/delete/{hotel}','HotelReport@buyingDelete')->name('delete.buying');

    Route::get('/inventory','HotelReport@inventory')->name('inventory');
    Route::resource('/construction-reports','ConstructionReportController');
    Route::get('/bill_Num','ConstructionReportController@bill_number');
    
    Route::get('/Addsalerecord','HotelSaleReportController@addhotelsale')->name('Addsalerecord');
    Route::post('/Addsalerecord','HotelSaleReportController@savehotelsale')->name('Savesalerecord');
    Route::post('/updateSaleRecord/{order}','HotelSaleReportController@updateSaleRecord')->name('updateSaleRecord');
    Route::post('/deleteSaleRecord/{order}','HotelSaleReportController@deleteSaleRecord')->name('deleteSaleRecord');
    
    
    Route::get('/savesalerecord','HotelSaleReportController@savehotelsale')->name('savesalerecord');
    
    Route::get('/construction-reports/{id}/delete','ConstructionReportController@delete');
    Route::post('/sale-report/data','HotelSaleReportController@data');
    Route::post('/sale-report/print','HotelSaleReportController@print');
    Route::resource('/construction-material','ConstructionMaterialController');
});

Route::group(['prefix'=>'admin','middleware'=>['auth','admin']],function (){
    Route::get('/', 'AdminController@index')->name('admin_home');
    Route::get('/create-member-ob','DbScriptController@create_member_ob');
    Route::get('/inser-ob-records','DbScriptController@inser_ob_records');
    Route::get('/insert-dimentions-record','DbScriptController@insert_dimentions_record');
    Route::get('/insert-coa-dimensions-record','DbScriptController@insert_coa_dimensions_record');
    Route::get('/mapServiceFeeToSubsFee','DbScriptController@map_service_charges_to_subscription_fee');
    Route::get('/insert-membership-fee-reg-fee','DbScriptController@insert_membership_fee_reg_fee');
    Route::get('/debit-credit-for-service-revenue-dec','DbScriptController@debit_credit_for_service_revenue_dec');
    Route::get('/update-subs-fee','DbScriptController@update_subs_fee');
    Route::get('/insert-oct-nov-fee-vouchers','DbScriptController@insert_oct_nov_fee_vouchers');
    Route::get('/insert-paid-vouchers-record','DbScriptController@insert_paid_vouchers_record');
    Route::get('/get-missing-ids','DbScriptController@get_missing_ids');
    Route::get('/get-zero-fee','DbScriptController@fee_zero');
    Route::get('/voucher-entry-script1','DbScriptController@voucher_entry_script1');
    Route::get('/voucher-entry-script2','DbScriptController@voucher_entry_script2');
    Route::get('/voucher-entry-script3','DbScriptController@voucher_entry_script3');
    Route::get('/set-email-pass-members','DbScriptController@set_email_pass_members');
    Route::get('/insert-joining-date','DbScriptController@insert_joining_date');
    /// Setting Area
    Route::get('/settings', 'AdminController@settings')->name('admin-settings');
    Route::get('/ledger','ManageLedgerReportController@index')->name('ledger-report');
    Route::get('/detailed-ledger','ManageDetailedLedgerReportController@index')->name('detail-ledger-report');
    Route::get('/member-fee-cleared','ManageLedgerReportController@member_fee_cleared')->name('member-fee-cleared');
    Route::get('/member-fee-pending','ManageLedgerReportController@member_fee_pending')->name('member-fee-pending');
    Route::post('/ledger/data','ManageLedgerReportController@data')->name('ledger-data');
    Route::post('/detailed-ledger/data','ManageDetailedLedgerReportController@data')->name('detail-ledger-data');
    Route::post('/ledger/print', 'ManageLedgerReportController@print');
    Route::post('/detailed-ledger/print','ManageDetailedLedgerReportController@print');
    Route::get('/check-pwd','AdminController@chkPassword');
    Route::post('/update-pwd','AdminController@updatAdminPwd');
    Route::get('/show-users','UserController@show')->name('all-users');
    Route::get('delete-user/{id}','UserController@destroy');
    Route::get('delete-member-user/{id}','MemberController@destroy');
    Route::get('/user/{id}','UserController@listByUsers')->name('users');
    Route::match(['put', 'patch'], '/update-user/{id}','UserController@UserUpdate')->name('user-update');
    Route::get('/create-user','UserController@create')->name('create-user');
    Route::post('/register_user','UserController@register');
    Route::resource('/employee-post','EmplyeePostController');
    Route::resource('/employees','EmployeeController');
    Route::resource('/employees-pay','EmyloyeePayController');
    Route::resource('/customers','CustomerController');
    Route::get('/show-customers/{membership_id}','MemberController@customerDetail')->name('customers-detail');
    Route::get('/payment-history','MemberController@PaymentsHistory')->name('payment-history');
    Route::get('/edit/{membership_id}','editprofile@edit')->name('edit-profile');
    Route::post('/edit/{membership_id}','editprofile@update')->name('update-user');
    Route::get('/addbill/{membership_id}','HotelReport@Storebill')->name('Add-billtoMember');
    Route::match(['put', 'patch'], '/customer-user/{members_id}','MemberController@CustomerUpdate')->name('customer-update');
    Route::resource('/memberspayrecord','MembersPayRecordController');
    //voucher entry-voucher.create
    Route::get('/entry-voucher/create','ManageVoucherController@index')->name('voucher.create');
    Route::post('/entry-voucher/store','ManageVoucherController@store')->name('voucher.store');
    Route::post('/entry-voucher/save','ManageVoucherController@save')->name('voucher.save');
    Route::get('/entry-voucher/show','ManageVoucherController@show')->name('voucher.index');
    Route::post('/addVoucher', 'ManageVoucherController@addVoucher');
    Route::post('/editVoucher', 'ManageVoucherController@editVoucher');
    Route::get('entry-voucher/{id}/view', 'ManageVoucherController@viewVoucher');
    Route::get('/edit/voucher/{id}','ManageVoucherController@edit')->name('voucher.edit');
    Route::get('/delete/voucher/{id}','ManageVoucherController@destroy')->name('voucher.delete');


    // sale report



    Route::get('/showhoteltotal','HotelReport@showtotal')->name('showhoteltotal');
    Route::get('/shgenbill','HotelReport@genbills')->name('genbill');
    Route::get('/BillGenrate','HotelReport@Genbill')->name('GenerateBill');


    Route::get('/newmemberfull','MemberController@reportnewmember')->name('newmember');

    Route::get('/bedmintonmem','MemberController@reportbedmintonmember')->name('bedmintonmembers');

    Route::get('/oldmemberreport','MemberController@oldmemberreport')->name('oldmember');
    Route::get('/veharimemberreport','MemberController@veharimemberreport')->name('veharimembers');
    Route::get('/showmember','HotelReport@showbill')->name('searchmemberbill');
    Route::post('/updateimage','editprofile@updateImage')->name('imageget');
    Route::get('/billadd','HotelReport@BillAdd')->name('bill-Add');
    Route::get('/uploadbill','HotelReport@uploadbill')->name('Upload-Bill');

    Route::get('/menu-hotel','hotelreport@menu')->name('hotelmenu');
    Route::get('/search-data','ConstructionReportController@search')->name('construction.search');
    Route::get('/search-by_bill_num','ConstructionReportController@search_by_BillNum')->name('search_by_bill');

    Route::get('/searchmemberforbill','HotelReport@searchmember')->name('searchmemberidinbill');
    Route::post('/search-MEMBERS','membersreport@searchmember')->name('searchmember');
    Route::get('/generatePDF','ConstructionReportController@generatePDF')->name('generatePDF');
    Route::get('/chart-of-accounts','Admin\ChartOfAccountController@index')->name('showChartOfAccount');

resources/views/backEnd/salary/create.blade.php
@extends('backEnd.layouts.master')
@section('title','Add Post')
@section('styles')
<link rel="stylesheet" href="{{asset('css/all.min.css')}}">
  <!-- Ionicons -->
   <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{{asset('css/tempusdominus-bootstrap-4.min.css')}}">
  <!-- iCheck -->
  <link href="{{asset('css/toastr.min.css')}}" rel="stylesheet" id="bootstrap-css">

  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('css/adminlte.min.css')}}">
  <link rel="stylesheet" href="{{asset('css/sweetalert.css')}}">
  <!-- summernote -->
  <link rel="stylesheet" href="{{asset('css/summernote-bs4.css')}}">
  <!-- Plugin css for this page -->
  <!-- endinject -->
  <link rel="shortcut icon" href="{{asset('images/favicon.png')}}" />
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
@endsection
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Add Users Post</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{url('/admin')}}">Home</a></li>
              <li class="breadcrumb-item active">Create New Post</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Create New Posts</h3>

              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                  <i class="fas fa-minus"></i></button>
              </div>
            </div>
            <form action="{{route('employee-post.store')}}" method="post">
              @csrf
            <div class="card-body">
              <div class="form-group">
                <label for="name">Post Title</label>
                <input type="text" id="title" name="title" class="form-control" value="{{old('title')}}">
                <span class="text-danger">{{$errors->first('title')}}</span>
              </div>

               <div class="form-group">
                <label for="name">Post Descriptions</label>
               <div class="mb-3">
                <textarea class="textarea" name="description" placeholder="Place some text here"
                          style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">{{$errors->first('description')}}</textarea>
              </div>
                <span class="text-danger">{{$errors->first('description')}}</span>
              </div>
              <div class="form-group">
                <input type="submit" value="Create new Post" class="btn btn-success float-right">
              </div>
            </div>
            </form>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
    
      </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@endsection
@section('jsblock')

<script>
  $(function () {
    // Summernote
    $('.textarea').summernote()
  })
</script>
<!-- overlayScrollbars -->

 <script type="text/javascript">
        @if (Session::has('success'))
        toastr.success("{{Session::get('success')}}");

        @endif
    </script>

@endsection

resources/views/backEnd/salary/index.blade.php
@extends('backEnd.layouts.master')
@section('title','All Posts')
@section('styles')
<link rel="stylesheet" href="{{asset('css/all.min.css')}}">
  <!-- Ionicons -->
   <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- iCheck -->
  <link href="{{asset('css/toastr.min.css')}}" rel="stylesheet" id="bootstrap-css">
<link href="{{asset('css/dataTables.bootstrap4.css')}}" rel="stylesheet" id="bootstrap-css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('css/adminlte.min.css')}}">
  <link rel="stylesheet" href="{{asset('css/sweetalert.css')}}">
  <!-- summernote -->
  <link rel="stylesheet" href="{{asset('css/summernote-bs4.css')}}">
  <!-- Plugin css for this page -->
  <!-- endinject -->
  <link rel="shortcut icon" href="{{asset('images/favicon.png')}}" />
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
@endsection
@section('content')
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>All Employees</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{url('/admin')}}">Home</a></li>
              <li class="breadcrumb-item active">All Registered Employees</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">

          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Employees Data</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Image</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Phone</th>
                  <th>Cnic No.</th>
                  <th>City</th>
                  <th>Address</th>
                  <th>Status</th>
                  <th>View</th>
                </tr>
                </thead>
                <tbody>
                  @foreach($employees as $employee)
                <tr>
                  <td><img src="{{url('images/employee/',$employee->image)}}" alt="" width="70"</td>
                  <td>{{$employee->name}}</td>
                  <td>{{$employee->email}}</td>
                  <td>{{$employee->phone}}</td>
                  <td>{{$employee->cnic}}</td>
                  <td>{{$employee->city}}</td>
                  <td>{{$employee->address}}</td>
                  <td>@if ($employee->status==0) 
<span class="badge bg-danger">Unactive</span>
@else
<span class="badge bg-success">Active</span>
@endif</td>
                  <td>
                      <a href="javascript:" rel="" rel1="delete-user" class="btn btn-danger btn-sm deleteRecord"><i class="fa fa-trash"></i></a>
                      <a href=""  class="btn btn-info btn-sm"><i class="fa fa-eye"></i></a>
                  </td>
                </tr>
                @endforeach
                </tbody>
               
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
@endsection
@section('jsblock')

<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->


    <script type="text/javascript">
        @if (Session::has('success'))

        toastr.success("{{Session::get('success')}}");
        @endif
    </script>
    <script>
  $(function () {
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
    <script>
            $(".deleteRecord").click(function () {
               var id=$(this).attr('rel');
               var deleteFunction=$(this).attr('rel1');
               swal({
                   title:'Are you sure?',
                   text:"You won't be able to revert this!",
                   type:'warning',
                   showCancelButton:true,
                   confirmButtonColor:'#3085d6',
                   cancelButtonColor:'#d33',
                   confirmButtonText:'Yes, delete it!',
                   cancelButtonText:'No, cancel!',
                   confirmButtonClass:'btn btn-success',
                   cancelButtonClass:'btn btn-danger',
                   buttonsStyling:false,
                   reverseButtons:true
               },function () {
                  window.location.href="/admin/"+deleteFunction+"/"+id;
               });
            });
        </script>
@endsection