routes/web.php
    Route::get('/chart-of-accounts','Admin\ChartOfAccountController@index')->name('showChartOfAccount');
    Route::get('/create/chart-of-accounts','Admin\ChartOfAccountController@create')->name('chartOfAccount.create');
    Route::post('/create/chart-of-accounts','Admin\ChartOfAccountController@store')->name('chartOfAccount.store');
    Route::get('/edit/chart-of-accounts/{id}','Admin\ChartOfAccountController@edit')->name('chartOfAccount.edit');
    Route::post('/update/chart-of-accounts/{id}','Admin\ChartOfAccountController@update')->name('chartOfAccount.update');
    Route::get('/delete/chart-of-accounts/{id}','Admin\ChartOfAccountController@delete')->name('chartOfAccount.delete');
    Route::get('/opening-balance/create','BalanceController@index')->name('balance.create');
    Route::post('/opening-balance/store','BalanceController@store')->name('balance.store');
    Route::get('/opening-balance/show','BalanceController@show')->name('balance.index');
    Route::get('delete-balance/{id}','BalanceController@destroy');
    Route::get('/edit/balance/{id}','BalanceController@edit')->name('balance.edit');
    Route::post('/balance/update/{id}','BalanceController@update')->name('balance.update');

    Route::get('/logs','LogsController@index')->name('logs');
    Route::get('/logs-data','LogsController@data')->name('logs-data');

});


/*
 *
 * Manager routes
 *
 * */
Route::group(['prefix'=>'manager','middleware'=>['auth','manager']], function (){
    Route::get('/','Manager\ManagerController@index');
    Route::get('/members/orders',[
        'as' => 'membersOrders',
        'uses' => 'Manager\MemberController@index'
    ]);
    Route::get('/show/product/data/{id}','Manager\MemberController@productShow');
});

/**
 * Member Routes
 */
Route::group(['prefix' => 'member','middleware'=>['auth','member']], function () {
    Route::get('/','Member\DashboardController@index');
    Route::get('/member-ledger', 'Member\MemberLedgerController@index');
});


/**
 * Secertry Routes
 */
Route::group(['prefix' => 'secertry','middleware'=>['auth','secertry']], function () {
    Route::get('/','Secertry\SecertryController@index');
    Route::get('/members/orders',[
        'as' => 'secertryMembersOrders',
        'uses' => 'Secertry\MemberController@index'
    ]);

    Route::get('/settings', 'Secertry\SecertryController@settings')->name('secertry-settings');
    Route::get('/check-pwd','Secertry\SecertryController@chkPassword');
    Route::post('/update-pwd','Secertry\SecertryController@updatSecertryPwd');

    Route::get('/show/product/data/{id}','Secertry\MemberController@productShow');

    Route::get('/logs','Secertry\LogsController@index')->name('secertrylogs');
    Route::get('/pendingApproval','Secertry\editprofile@index')->name('pendingapproval');
    Route::get('/ApproveProfile/{membership_id}','Secertry\editprofile@update')->name('approve-profile');

    Route::get('/voucherApproval','Secertry\ManageVoucherController@show')->name('voucherapproval');
    Route::get('/approveVoucher/{id}','Secertry\ManageVoucherController@addVoucher')->name('approve-voucher');
    Route::get('/voucherApproval/{id}/vieww', 'Secertry\ManageVoucherController@viewVoucher');
    
    Route::get('/show-customers/{membership_id}','Secertry\MemberController@customerDetail')->name('secertrycustomers-detail');
});


/**
 * Operator Routes
 */
Route::group(['prefix' => 'operator','middleware'=>['auth','operator']], function () {
    Route::get('/','Operator\OperatorController@index');
    Route::get('/memberspayrecord','Operator\MembersPayRecordController@index')->name('operatorMemberspayrecord.index');
    Route::get('/memberspayrecord/create','Operator\MembersPayRecordController@create')->name('operatorMemberspayrecord.create');
    Route::get('/memberspayrecord/store','Operator\MembersPayRecordController@store')->name('operatorMemberspayrecord.store');
    Route::get('/show-customers/{membership_id}','Operator\MemberController@customerDetail')->name('operatorcustomers-detail');
    Route::get('/edit/{membership_id}','Operator\editprofile@edit')->name('operatoredit-profile');
    Route::post('/edit/{membership_id}','Operator\editprofile@update')->name('operatorupdate-user');

    Route::get('/payment-history','Operator\MemberController@PaymentsHistory')->name('operatorPayment-history');

    Route::get('/chart-of-accounts','Operator\ChartOfAccountController@index')->name('operatorShowChartOfAccount');
    Route::get('/create/chart-of-accounts','Operator\ChartOfAccountController@create')->name('operatorChartOfAccount.create');
    Route::post('/create/chart-of-accounts','Operator\ChartOfAccountController@store')->name('operatorChartOfAccount.store');
    Route::get('/edit/chart-of-accounts/{id}','Operator\ChartOfAccountController@edit')->name('operatorChartOfAccount.edit');
    Route::post('/update/chart-of-accounts/{id}','Operator\ChartOfAccountController@update')->name('operatorChartOfAccount.update');
    Route::get('/delete/chart-of-accounts/{id}','Operator\ChartOfAccountController@delete')->name('operatorChartOfAccount.delete');
    
    Route::resource('/operator-employee-post','Operator\EmplyeePostController');
    Route::resource('/operator-employees','Operator\EmployeeController');
    Route::resource('/operator-employees-pay','Operator\EmyloyeePayController');
    
    Route::get('/user/{id}','Operator\UserController@listByUsers')->name('operator-users');
    Route::get('/delete-user/{id}','Operator\UserController@destroy');
    Route::match(['put', 'patch'], '/update-user/{id}','Operator\UserController@UserUpdate')->name('operator-user-update');
    
    Route::resource('/operator-construction-reports','Operator\ConstructionReportController');
    Route::get('/operator-bill_Num','Operator\ConstructionReportController@bill_number');
    Route::get('/operator-construction-reports/{id}/delete','Operator\ConstructionReportController@delete');
    Route::resource('/operator-construction-material','Operator\ConstructionMaterialController');
    Route::get('/search-data','Operator\ConstructionReportController@search')->name('operator-construction.search');
    Route::get('/search-by_bill_num','Operator\ConstructionReportController@search_by_BillNum')->name('operator-search_by_bill');
    Route::get('/generatePDF','Operator\ConstructionReportController@generatePDF')->name('operator-generatePDF');
    
    Route::get('/searchmemberforbill','Operator\HotelReport@searchmember')->name('operator-searchmemberidinbill');
    Route::get('/operator-hotel-sale-report','Operator\HotelSaleReportController@index');
    Route::get('/operator-hotel-sale-report/edit/{order}','Operator\HotelSaleReportController@editSale');
    Route::get('/AddhotelBuying','Operator\HotelReport@buyingadd')->name('operator-addbuying');
    Route::get('/search-data-hotel','Operator\HotelBuyingController@search')->name('operator-searchhotelbuyingreport');
    Route::get('/search-inventory-hotel','Operator\HotelBuyingController@inventoryReport')->name('operator-inventoryReport');
    Route::get('/totalBuying','Operator\HotelReport@buying')->name('operator-buying');
    Route::get('/totalBuying/edit/{hotel}','Operator\HotelReport@buyingEdit')->name('edit.operator-buying');
    Route::post('/totalBuying/edit/{hotel}','Operator\HotelReport@buyingUpdate')->name('update.operator-buying');
    Route::post('/totalBuying/delete/{hotel}','Operator\HotelReport@buyingDelete')->name('delete.operator-buying');
    Route::get('/buyingItem','Operator\HotelBuyingItemController@index')->name('operator-buyingItem');
    Route::post('/operator-buy-report/print','Operator\HotelBuyingItemController@print');
    Route::post('/operator-buy-report/data','Operator\HotelBuyingItemController@data');
    Route::post('/operator-sale-report/data','Operator\HotelSaleReportController@data');
    Route::post('/operator-sale-report/print','Operator\HotelSaleReportController@print');
    Route::get('/create-buying-item','Operator\HotelBuyingItemController@create')->name('operator-createBuyingItem');
    Route::post('/store-buying-item','Operator\HotelBuyingItemController@store')->name('operator-storeBuyingItem');
    Route::post('/savehotelBuying','Operator\HotelBuyingController@buyingsave')->name('operator-savehotelbuying');
    Route::post('/updateKitchItem','Operator\HotelBuyingController@updateKitchItem')->name('operator-updateKitchItem');
    Route::get('/Addsalerecord','Operator\HotelSaleReportController@addhotelsale')->name('operator-Addsalerecord');
    Route::post('/Addsalerecord','Operator\HotelSaleReportController@savehotelsale')->name('operator-Savesalerecord');
    Route::post('/updateSaleRecord/{order}','Operator\HotelSaleReportController@updateSaleRecord')->name('operator-updateSaleRecord');
    Route::post('/deleteSaleRecord/{order}','Operator\HotelSaleReportController@deleteSaleRecord')->name('operator-deleteSaleRecord');
    Route::resource('/operator-products','Operator\ProductsController');
    Route::resource('/operator-categories', 'Operator\CategoriesController');
    Route::get('/operator-inventory','Operator\HotelReport@inventory')->name('operator-inventory');
    
    Route::get('/shgenbill','HotelReport@genbills')->name('operator-genbill');
    Route::get('/BillGenrate','Operator\HotelReport@Genbill')->name('operator-GenerateBill');

    Route::get('/entry-voucher/create','Operator\ManageVoucherController@index')->name('operatorvoucher.create');
    Route::post('/entry-voucher/store','Operator\ManageVoucherController@store')->name('operatorvoucher.store');
    Route::post('/entry-voucher/save','Operator\ManageVoucherController@save')->name('operatorvoucher.save');
    Route::get('/entry-voucher/show','Operator\ManageVoucherController@show')->name('operatorvoucher.index');
    Route::post('/addVoucher', 'Operator\ManageVoucherController@addVoucher');
    Route::post('/editVoucher', 'Operator\ManageVoucherController@editVoucher');

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Category::all();
        return view('backEnd.categories.index',compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backEnd.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required',
            'description'=>'required',
       ]);
       Category::create([
            'name' => $request->get('name'),
            'description' => $request->get('description')
       ]);
       return redirect('/categories');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Category::where('id',$id)->first();
        return view('backEnd.categories.edit',compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $update = ['name' => $request->get('name'), 'description' => $request->get('description')];
        Category::where('id',$id)->update($update);
        return redirect('/categories');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::where('id',$id)->delete();
        return redirect('/categories');
    }
}

app/Http/Controllers/Operator/CategoriesController.php
<?php

namespace App\Http\Controllers\Operator;
use App\Http\Controllers\Controller;

use App\Category;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Category::all();
        return view('operator.categories.index',compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('operator.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required',
            'description'=>'required',
       ]);
       Category::create([
            'name' => $request->get('name'),
            'description' => $request->get('description')
       ]);
       return redirect('/operator-categories');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Category::where('id',$id)->first();
        return view('operator.categories.edit',compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $update = ['name' => $request->get('name'), 'description' => $request->get('description')];
        Category::where('id',$id)->update($update);
        return redirect('/operator-categories');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::where('id',$id)->delete();
        return redirect('/operator-categories');
    }
}

app/Http/Controllers/Operator/ConstructionMaterialController.php
<?php

namespace App\Http\Controllers\Operator;
use App\Http\Controllers\Controller;

use App\ConstructionMaterial;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Audit;
use Auth;

class ConstructionMaterialController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $constructionMaterial=ConstructionMaterial::all();
        $logged_in_user = Auth::user();
        $logged_in_user = $logged_in_user->id;
        $routeName = url()->current();

        $audit_create = new Audit();
        $audit_create->user_id = $logged_in_user;
        $audit_create->action = "Construction Material";
        $audit_create->route = $routeName;
        $audit_create->save();
        return view('operator.construction.material_create', compact('constructionMaterial'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[
            'mat_name'=>'required',
        ]);
        $material=$request->input('mat_name');
        DB::table('construction_material')->insert(
            ['mat_name' => $material,'created_at'=>now(),'updated_at'=>now()]
        );
        $logged_in_user = Auth::user();
        $logged_in_user = $logged_in_user->id;
        $routeName = url()->current();

        $audit_create = new Audit();
        $audit_create->user_id = $logged_in_user;
        $audit_create->action = "Construction Material Store";
        $audit_create->route = $routeName;
        $audit_create->save();
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ConstructionMaterial  $constructionMaterial
     * @return \Illuminate\Http\Response
     */
    public function show(ConstructionMaterial $constructionMaterial)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ConstructionMaterial  $constructionMaterial
     * @return \Illuminate\Http\Response
     */
    public function edit(ConstructionMaterial $constructionMaterial)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ConstructionMaterial  $constructionMaterial
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ConstructionMaterial $constructionMaterial)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ConstructionMaterial  $constructionMaterial
     * @return \Illuminate\Http\Response
     */
    public function destroy(ConstructionMaterial $constructionMaterial)
    {
        //
    }
}

resources/views/operator/categories/index.blade.php
@extends('operator.layouts.master')
@section('title','List Categories')
@section('styles')
 <link rel="stylesheet" href="{{asset('css/all.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- daterange picker -->
  <link rel="stylesheet" href="{{asset('css/daterangepicker.css')}}">
  <!-- iCheck for checkboxes and radio inputs -->
  <link rel="stylesheet" href="{{asset('css/icheck-bootstrap.min.css')}}">
  <!-- Bootstrap Color Picker -->
  <link rel="stylesheet" href="{{asset('css/bootstrap-colorpicker.min.css')}}">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{{asset('css/tempusdominus-bootstrap-4.min.css')}}">
  <!-- Select2 -->
  <link rel="stylesheet" href="{{asset('css/select2.min.css')}}">
  <link rel="stylesheet" href="{{asset('css/select2-bootstrap4.min.css')}}">
  <!-- Bootstrap4 Duallistbox -->
  <link rel="stylesheet" href="{{asset('css/bootstrap-duallistbox.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('css/toastr.min.css')}}">
  <link rel="stylesheet" href="{{asset('css/adminlte.min.css')}}">
  <link rel="shortcut icon" href="{{asset('images/favicon.png')}}" />
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <link href="{{asset('css/dataTables.bootstrap4.css')}}" rel="stylesheet" id="bootstrap-css">

@endsection
@section('content')
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Hotel buying Data</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active"> Categories</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">

          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Categories</h3>
            </div>
            <div class="col-md-12">
                <a class="btn btn-success float-right" href="{{route('operator-categories.create')}}"> Add New</a>
            </div>
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th style="width:50px">Action</th>
                </tr>
                </thead>
                <tbody>
               @foreach($items as $item)
               <tr>
                  <td>{{$item->id}}</td>
                  <td>{{$item->name}}</td>
                  <td>{{$item->description}}</td>
                  <td><a href="{{route('operator-categories.edit',[$item->id])}}" class="btn btn-sm btn-outline-success">Edit</a>
                    /
                    <form action="{{ route('operator-categories.destroy', $item->id)}}" method="post">
                        {{ csrf_field() }}
                        @method('DELETE')
                        <button class="btn btn-sm btn-outline-danger" id="deleteBtn" type="submit">Delete</button>
                    </form>
                </tr>
                @endforeach
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>

    <!-- /.content -->
  </div>
@endsection
@section('jsblock')

 <script type="text/javascript">
        @if (Session::has('success'))
        toastr.success("{{Session::get('success')}}");

        @endif
    </script>
    <script>
  $(function () {
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
<script>
  $(function () {
    //   $('#deleteBtn').on('click',function(){
    //     confirm('Do you really want to delete this?');
    //   });
    //Initialize Select2 Elements
    $('.select2').select2()

    //Initialize Select2 Elements
    $('.select2bs4').select2({
      theme: 'bootstrap4'
    })

    //Datemask dd/mm/yyyy
    $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
    //Datemask2 mm/dd/yyyy
    $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })
    //Money Euro
    $('[data-mask]').inputmask()

    //Date range picker
    $('#reservation').daterangepicker()
    //Date range picker with time picker
    $('#reservationtime').daterangepicker({
      timePicker: true,
      timePickerIncrement: 30,
      locale: {
        format: 'MM/DD/YYYY hh:mm A'
      }
    })
    //Date range as a button
    $('#daterange-btn').daterangepicker(
      {
        ranges   : {
          'Today'       : [moment(), moment()],
          'Yesterday'   : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
          'Last 7 Days' : [moment().subtract(6, 'days'), moment()],
          'Last 30 Days': [moment().subtract(29, 'days'), moment()],
          'This Month'  : [moment().startOf('month'), moment().endOf('month')],
          'Last Month'  : [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        startDate: moment().subtract(29, 'days'),
        endDate  : moment()
      },
      function (start, end) {
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
      }
    )

    //Timepicker
    $('#timepicker').datetimepicker({
      format: 'LT'
    })

    //Bootstrap Duallistbox
    $('.duallistbox').bootstrapDualListbox()

    //Colorpicker
    $('.my-colorpicker1').colorpicker()
    //color picker with addon
    $('.my-colorpicker2').colorpicker()

    $('.my-colorpicker2').on('colorpickerChange', function(event) {
      $('.my-colorpicker2 .fa-square').css('color', event.color.toString());
    });

    $("input[data-bootstrap-switch]").each(function(){
      $(this).bootstrapSwitch('state', $(this).prop('checked'));
    });

  })
</script>
@endsection